In [39]:
import pandas as pd
import numpy as np

### Load the data

In [40]:
df = pd.read_csv('../data/HIV_dataset.csv')
df.head()

,Age,Marital Staus,STD,Educational Background,HIV TEST IN PAST YEAR,AIDS education,Places of seeking sex partners,SEXUAL ORIENTATION,Drug- taking,Result
0,22,UNMARRIED,NO,College Degree,YES,NO,Bar,Heterosexual,YES,POSITIVE
1,20,UNMARRIED,NO,College Degree,NO,YES,NaN,Heterosexual,NO,NEGATIVE
2,23,Married,YES,College Degree,NO,YES,NaN,Bisexual,NO,NEGATIVE
3,24,Married,NO,College Degree,YES,YES,Park,Heterosexual,YES,POSITIVE
4,18,UNMARRIED,YES,Senior High School,YES,NO,Internet,Heterosexual,YES,POSITIVE

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             698 non-null    int64
 1   Marital Staus                   698 non-null    str
 2   STD                             698 non-null    str
 3   Educational Background          698 non-null    str
 4   HIV TEST IN PAST YEAR           698 non-null    str
 5   AIDS education                  698 non-null    str
 6   Places of seeking sex partners  676 non-null    str
 7   SEXUAL ORIENTATION              698 non-null    str
 8   Drug- taking                    698 non-null    str
 9   Result                          698 non-null    str
dtypes: int64(1), str(9)
memory usage: 94.2 KB

In [42]:
df.duplicated().sum()

np.int64(345)

In [43]:
df.drop_duplicates(inplace=True)

In [44]:
df.isna().sum()

Age                                0
Marital Staus                      0
STD                                0
Educational Background             0
HIV TEST IN PAST YEAR              0
AIDS education                     0
Places of seeking sex partners    13
SEXUAL ORIENTATION                 0
Drug- taking                       0
Result                             0
dtype: int64

### inspect columns or errors in columns

In [45]:
df.describe(include='all')

,Age,Marital Staus,STD,Educational Background,HIV TEST IN PAST YEAR,AIDS education,Places of seeking sex partners,SEXUAL ORIENTATION,Drug- taking,Result
count,353.000000,353,353,353,353,353,340,353,353,353
unique,NaN,7,4,6,2,4,6,5,4,4
top,NaN,UNMARRIED,NO,College Degree,NO,NO,Internet,Heterosexual,NO,NEGATIVE
freq,NaN,142,182,108,216,205,100,189,198,175
mean,39.651558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,18.235373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,12.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,37.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,54.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,80.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df['Drug- taking'].value_counts()

Drug- taking
NO     198
YES    148
No       4
Yes      3
Name: count, dtype: int64

#### convert all columns to lowercase

In [47]:
df.columns = df.columns.str.lower().str.strip().str.replace(' ','_')

#### convert all non numeric rows to lower case

In [48]:
non_num = df.select_dtypes('object').columns
for col in non_num:
    df[col] = df[col].str.lower()

C:\Users\dunsin\AppData\Local\Temp\ipykernel_10912\1904635605.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  non_num = df.select_dtypes('object').columns

### Age

In [49]:
df

,age,marital_staus,std,educational_background,hiv_test_in_past_year,aids_education,places_of_seeking_sex_partners,sexual_orientation,drug-_taking,result
0,22,unmarried,no,college degree,yes,no,bar,heterosexual,yes,positive
1,20,unmarried,no,college degree,no,yes,NaN,heterosexual,no,negative
2,23,married,yes,college degree,no,yes,NaN,bisexual,no,negative
3,24,married,no,college degree,yes,yes,park,heterosexual,yes,positive
4,18,unmarried,yes,senior high school,yes,no,internet,heterosexual,yes,positive
...,...,...,...,...,...,...,...,...,...,...
351,23,married,yes,college degree,no,yes,NaN,bisexual,no,negative
352,24,married,no,college degree,yes,no,park,heterosexual,yes,positive
353,18,unmarried,yes,senior high school,yes,no,internet,heterosexual,yes,positive
354,15,unmarried,no,junior high school,no,no,public bath,bisexual,no,negative
355,15,unmarried,yes,junior high school,no,no,public bath,heterosexual,no,negative

In [50]:
df['age'].unique()

array([22, 20, 23, 24, 18, 15, 70, 44, 13, 19, 25, 75, 50, 76, 34, 45, 56,
       27, 29, 40, 78, 16, 26, 37, 12, 67, 21, 30, 71, 80, 35, 68, 17, 38,
       46, 42, 41, 28, 64, 69, 73, 14, 49, 43, 47, 39, 36, 31, 32, 79, 57,
       51, 48, 33, 59, 62, 54, 52, 61, 58, 53, 60, 65, 66, 55])

In [51]:
df['age'].value_counts()

age
15    22
34    18
45    17
56    15
23    14
      ..
64     1
73     1
48     1
58     1
53     1
Name: count, Length: 65, dtype: int64

### marital status

In [52]:
df.rename(columns={'marital_staus' : 'marital_status'} , inplace=True)

In [53]:
df['marital_status'].value_counts()

marital_status
unmarried     142
married       102
divorced       51
widowed        40
cohabiting     18
Name: count, dtype: int64

In [54]:
df['marital_status'].isna().sum()

np.int64(0)

### std

In [55]:
df['std'].unique()

<ArrowStringArray>
['no', 'yes']
Length: 2, dtype: str

In [56]:
df['std'].value_counts()

std
no     186
yes    167
Name: count, dtype: int64

### educational background

In [57]:
df['educational_background'].unique()

<ArrowStringArray>
[    'college degree', 'senior high school', 'junior high school',
         'illiteracy',     'primary school',    'college dregree']
Length: 6, dtype: str

In [58]:
df['educational_background'].value_counts()

educational_background
college degree        108
senior high school     69
junior high school     69
illiteracy             54
primary school         40
college dregree        13
Name: count, dtype: int64

In [59]:
df['educational_background'] = df['educational_background'].replace({'college dregree' :'college degree'})

In [60]:
df['educational_background'].value_counts()

educational_background
college degree        121
senior high school     69
junior high school     69
illiteracy             54
primary school         40
Name: count, dtype: int64

### hiv_test_in_past_year

In [61]:
df['hiv_test_in_past_year'].unique()

<ArrowStringArray>
['yes', 'no']
Length: 2, dtype: str

### aids_education

In [62]:
df['aids_education'].unique()

<ArrowStringArray>
['no', 'yes']
Length: 2, dtype: str

### place of seeking for sex

In [63]:
df['places_of_seeking_sex_partners'].unique()

<ArrowStringArray>
['bar', nan, 'park', 'internet', 'public bath', 'others']
Length: 6, dtype: str

In [64]:
df [ df['places_of_seeking_sex_partners'].isna() ]  ### we will handle this during modelling

,age,marital_status,std,educational_background,hiv_test_in_past_year,aids_education,places_of_seeking_sex_partners,sexual_orientation,drug-_taking,result
1,20,unmarried,no,college degree,no,yes,NaN,heterosexual,no,negative
2,23,married,yes,college degree,no,yes,NaN,bisexual,no,negative
159,13,unmarried,no,primary school,no,no,NaN,heterosexual,no,negative
190,59,divorced,no,junior high school,yes,yes,NaN,heterosexual,no,negative
195,54,unmarried,no,college degree,no,yes,NaN,heterosexual,yes,negative
199,41,divorced,no,junior high school,yes,no,NaN,bisexual,no,negative
205,53,widowed,no,junior high school,no,no,NaN,bisexual,no,negative
208,50,unmarried,no,primary school,yes,yes,NaN,heterosexual,no,positive
212,60,unmarried,yes,senior high school,yes,yes,NaN,heterosexual,no,positive
218,33,widowed,yes,illiteracy,no,no,NaN,homosexual,yes,positive
244,41,married,yes,senior high school,no,yes,NaN,bisexual,yes,positive
350,20,unmarried,no,college degree,no,yes,NaN,heterosexual,no,negative
351,23,married,yes,college degree,no,yes,NaN,bisexual,no,negative

### Sexual orientation

In [65]:
df['sexual_orientation'].unique()

<ArrowStringArray>
['heterosexual', 'bisexual', 'homosexual', 'hetersexual']
Length: 4, dtype: str

In [66]:
df['sexual_orientation'].value_counts()

sexual_orientation
heterosexual    189
homosexual       86
bisexual         76
hetersexual       2
Name: count, dtype: int64

In [67]:
df['sexual_orientation'] = df['sexual_orientation'].replace({'hetersexual': 'heterosexual'} )

In [68]:
df['sexual_orientation'].value_counts()

sexual_orientation
heterosexual    191
homosexual       86
bisexual         76
Name: count, dtype: int64

drug taking

In [69]:
df.rename(columns={'drug-_taking' : 'drug_taking'}, inplace=True)

In [70]:
df['drug_taking'].unique()

<ArrowStringArray>
['yes', 'no']
Length: 2, dtype: str

### result

In [71]:
df['result'].unique()

<ArrowStringArray>
['positive', 'negative']
Length: 2, dtype: str

In [72]:
df.duplicated().sum()

np.int64(4)

In [73]:
df.drop_duplicates(inplace=True)

### Save the data

In [74]:
df.to_csv('../data/hiv_preprocessed_data.csv' ,  index=False)

### load the data

In [75]:
p_df = pd.read_csv('../data/hiv_preprocessed_data.csv')
p_df.head()

,age,marital_status,std,educational_background,hiv_test_in_past_year,aids_education,places_of_seeking_sex_partners,sexual_orientation,drug_taking,result
0,22,unmarried,no,college degree,yes,no,bar,heterosexual,yes,positive
1,20,unmarried,no,college degree,no,yes,NaN,heterosexual,no,negative
2,23,married,yes,college degree,no,yes,NaN,bisexual,no,negative
3,24,married,no,college degree,yes,yes,park,heterosexual,yes,positive
4,18,unmarried,yes,senior high school,yes,no,internet,heterosexual,yes,positive

In [76]:
p_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 349 entries, 0 to 348
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             349 non-null    int64
 1   marital_status                  349 non-null    str
 2   std                             349 non-null    str
 3   educational_background          349 non-null    str
 4   hiv_test_in_past_year           349 non-null    str
 5   aids_education                  349 non-null    str
 6   places_of_seeking_sex_partners  338 non-null    str
 7   sexual_orientation              349 non-null    str
 8   drug_taking                     349 non-null    str
 9   result                          349 non-null    str
dtypes: int64(1), str(9)
memory usage: 47.2 KB

In [77]:
p_df.duplicated().sum()

np.int64(0)